name = "ZetaSimpleZeros"
version = "0.1.0"
defaultTargets = ["ZetaSimpleZeros"]

[leanOptions]
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "51e6992efd06126df61a496bebf8f49482a4e129"

[[lean_lib]]
name = "ZetaSimpleZeros"
